# Generated by Django 4.1.1 on 2023-04-22 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('matricula', models.CharField(max_length=40)),
                ('turno', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeModalidade', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAluno', models.CharField(max_length=120)),
                ('matricula', models.CharField(max_length=120)),
                ('autorizado', models.BooleanField(default=False)),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigsportAPI.modalidade')),
            ],
        ),
    ]
