# Generated by Django 4.1.1 on 2023-04-22 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigsportAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaModalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='matricula',
            name='tipoCategoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sigsportAPI.categoriamodalidade'),
        ),
    ]
